### ISSUE TITLE
pdf typos

### ISSUE THREAD

**Issue by jdegand** [anttiviljami/product-engineer-manifesto#2]
-  "simply" is misspelled on page `02` on the second to last line.
-   On page `03`, semi-colon in this sentence  `While AI didn't create the product engineer role (examples have
been around for much longer); `  should be replaced with a comma.  It may be better to remove the parentheses bit for sentence flow and clarity.

**Comment by anttiviljami** [comment]
Thank you @jdegand!

Fixed the misspelling and improved the sentence on page 03. I ended up going with em dashes to set off the middle clause for better flow and clarity:

> While AI didn't create the product engineer role—examples have been around for much longer—AI has made becoming a true product engineer much more accessible as a career path for software engineers.

**Comment by anttiviljami** [comment]
I've also added a public link to the canva sources if you want to propose more edits :) 

https://www.canva.com/design/DAGJPOcuJpQ/h_M8ygUIFYRiTUAkZ7xMBg/edit?utm_content=DAGJPOcuJpQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
